# Generated by Django 5.1.7 on 2025-03-26 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=100, unique=True)),
                ('style_of_cause', models.CharField(max_length=1024)),
                ('citation', models.CharField(max_length=255)),
                ('citation_type', models.CharField(choices=[('neutral', 'Neutral'), ('canlii', 'CanLII'), ('other', 'Other')], default='neutral', max_length=20)),
                ('official_reporter_citation', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.IntegerField()),
                ('court', models.CharField(max_length=20)),
                ('decision_number', models.IntegerField()),
                ('jurisdiction', models.CharField(max_length=100)),
                ('court_name', models.CharField(max_length=255)),
                ('court_level', models.CharField(max_length=100)),
                ('short_url', models.URLField()),
                ('language', models.CharField(max_length=50)),
                ('docket_number', models.BigIntegerField()),
                ('decision_date', models.DateTimeField()),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('cited_cases', models.JSONField(blank=True, default=list)),
                ('citing_cases', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Offence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=50, unique=True)),
                ('offence_name', models.CharField(max_length=255)),
                ('minimum_summary', models.TextField()),
                ('maximum_summary', models.TextField()),
                ('minimum_indictable', models.TextField()),
                ('maximum_indictable', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FactPattern',
            fields=[
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data_processing.casemetadata')),
                ('canlii_keywords', models.JSONField(blank=True, default=list)),
                ('canlii_categories', models.JSONField(blank=True, default=list)),
                ('local_categories', models.JSONField(blank=True, default=list)),
                ('canlii_ai_summary', models.JSONField(blank=True, null=True)),
                ('local_ai_summary', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SentencingRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255, unique=True)),
                ('section', models.CharField(max_length=50)),
                ('offender', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('jail', models.TextField(blank=True)),
                ('mode', models.CharField(blank=True, max_length=255)),
                ('conditions', models.TextField(blank=True)),
                ('fine', models.CharField(blank=True, max_length=100)),
                ('appeal', models.BooleanField(default=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_processing.casemetadata')),
            ],
        ),
    ]
