# Generated by Django 5.1.7 on 2025-03-26 01:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casemetadata',
            options={'ordering': ['-decision_date', 'case_id']},
        ),
        migrations.AlterModelOptions(
            name='factpattern',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='offence',
            options={'ordering': ['section']},
        ),
        migrations.AlterModelOptions(
            name='sentencingrange',
            options={'ordering': ['-date', 'section']},
        ),
        migrations.AddField(
            model_name='casemetadata',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='casemetadata',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='factpattern',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='factpattern',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='offence',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='offence',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sentencingrange',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sentencingrange',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='casemetadata',
            name='decision_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sentencingrange',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
