# Generated by Django 5.1.7 on 2025-03-26 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0002_alter_casemetadata_options_alter_factpattern_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casemetadata',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casemetadata',
            name='court_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='casemetadata',
            name='court_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='casemetadata',
            name='decision_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casemetadata',
            name='decision_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='casemetadata',
            name='docket_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='casemetadata',
            name='short_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casemetadata',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
