# Generated by Django 5.1.7 on 2025-03-27 22:44

from django.db import migrations
from django.contrib.postgres.fields import ArrayField
from django.db.models import CharField

def convert_json_to_array(apps, schema_editor):
    CaseMetadata = apps.get_model('data_processing', 'CaseMetadata')
    FactPattern = apps.get_model('data_processing', 'FactPattern')
    
    # Convert CaseMetadata fields
    for case in CaseMetadata.objects.all():
        if isinstance(case.categories, list):
            case.categories = case.categories
        else:
            case.categories = []
            
        if isinstance(case.keywords, list):
            case.keywords = case.keywords
        else:
            case.keywords = []
        case.save()
    
    # Convert FactPattern fields
    for fact in FactPattern.objects.all():
        if isinstance(fact.canlii_categories, list):
            fact.canlii_categories = fact.canlii_categories
        else:
            fact.canlii_categories = []
            
        if isinstance(fact.canlii_keywords, list):
            fact.canlii_keywords = fact.canlii_keywords
        else:
            fact.canlii_keywords = []
        fact.save()

class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0004_alter_casemetadata_categories_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_json_to_array),
    ]
